version: '3'

services:
  zeppy-app:
    image: carrotww/zeppy:1.0.1
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_NAME=${DB_NAME}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_LOCAL_USERNAME=${POSTGRESQL_LOCAL_USERNAME}
      - POSTGRESQL_LOCAL_PASSWORD=${POSTGRESQL_LOCAL_PASSWORD}
      - POSTGRESQL_IP=${POSTGRESQL_IP}
      - POSTGRESQL_DEV_USERNAME=${POSTGRESQL_DEV_USERNAME}
      - POSTGRESQL_DEV_PASSWORD=${POSTGRESQL_DEV_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_IP=${REDIS_IP}
      - BACKEND_URL=${BACKEND_URL}
      - KAKAO_LOGIN_CLIENT_ID=${KAKAO_LOGIN_CLIENT_ID}
      - KAKAO_LOGIN_CLIENT_SECRET=${KAKAO_LOGIN_CLIENT_SECRET}
      - GOOGLE_LOGIN_CLIENT_ID=${GOOGLE_LOGIN_CLIENT_ID}
      - GOOGLE_LOGIN_CLIENT_SECRET=${GOOGLE_LOGIN_CLIENT_SECRET}
      - JWT_SECRETKEY=${JWT_SECRETKEY}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_ACCESS_HEADER=${JWT_ACCESS_HEADER}
      - JWT_ACCESS_TOKEN_NAME=${JWT_ACCESS_TOKEN_NAME}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      - JWT_REFRESH_HEADER=${JWT_REFRESH_HEADER}
      - JWT_REFRESH_TOKEN_NAME=${JWT_REFRESH_TOKEN_NAME}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
    networks:
      - zeppy-network

networks:
  zeppy-network:
    driver: bridge