spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always
# common: common
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /docs/openapi.yml
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true